-- PERSONS
INSERT INTO PERSONS (ID, NAME, SURNAME, JOB, EMAIL) VALUES (999, 'Vanda', 'Fonseca', 'Directora de recursos humanos', 'vandafonseca@email.com');
INSERT INTO PERSONS (ID, NAME, SURNAME, JOB, EMAIL) VALUES (998, 'Nolberto', 'Tovar', 'Técnico de selección de personas', 'nolbertotovar@email.com');
INSERT INTO PERSONS (ID, NAME, SURNAME, JOB, EMAIL) VALUES (997, 'Edelia', 'Ledesma', 'Consultor de reclutamiento independiente', 'edelialedesma@email.com');
INSERT INTO PERSONS (ID, NAME, SURNAME, JOB, EMAIL) VALUES (996, 'Harold', 'Mojica', 'Técnico de formación', 'haroldmojica@email.com');
INSERT INTO PERSONS (ID, NAME, SURNAME, JOB, EMAIL) VALUES (995, 'Tácito', 'Zamora', 'Técnico de TIC', 'tacitozamora@email.com');
INSERT INTO PERSONS (ID, NAME, SURNAME, JOB, EMAIL) VALUES (994, 'Máximo', 'Baez', 'Técnico de cmunicación interna', 'maximobaez@email.com');
INSERT INTO PERSONS (ID, NAME, SURNAME, JOB, EMAIL) VALUES (993, 'Mariela', 'Griego', 'Técnico de TIC', 'marielagriego@email.com');
INSERT INTO PERSONS (ID, NAME, SURNAME, JOB, EMAIL) VALUES (992, 'Rut', 'Mejía', 'Técnico de selección de personas', 'rutmejia@email.com');

-- ROOMS
INSERT INTO ROOMS (ID, FLOOR, NUMBER, NAME, SIZE, TV, PROJECTOR, SPEAKER) VALUES (999, 0, 1, 'Verde', 4, FALSE, TRUE, FALSE);
INSERT INTO ROOMS (ID, FLOOR, NUMBER, NAME, SIZE, TV, PROJECTOR, SPEAKER) VALUES (998, 0, 2, 'Rojo', 8, TRUE, FALSE, FALSE);
INSERT INTO ROOMS (ID, FLOOR, NUMBER, NAME, SIZE, TV, PROJECTOR, SPEAKER) VALUES (997, 1, 1, 'Amarillo', 2, FALSE, FALSE, FALSE);
INSERT INTO ROOMS (ID, FLOOR, NUMBER, NAME, SIZE, TV, PROJECTOR, SPEAKER) VALUES (996, 1, 2, 'Marrón', 6, FALSE, TRUE, TRUE);
INSERT INTO ROOMS (ID, FLOOR, NUMBER, NAME, SIZE, TV, PROJECTOR, SPEAKER) VALUES (995, 1, 3, 'Azul', 3, FALSE, FALSE, FALSE);
INSERT INTO ROOMS (ID, FLOOR, NUMBER, NAME, SIZE, TV, PROJECTOR, SPEAKER) VALUES (994, 1, 4, 'Blanco', 10, TRUE, FALSE, FALSE);
INSERT INTO ROOMS (ID, FLOOR, NUMBER, NAME, SIZE, TV, PROJECTOR, SPEAKER) VALUES (993, 2, 1, 'Negro', 6, FALSE, TRUE, FALSE);
INSERT INTO ROOMS (ID, FLOOR, NUMBER, NAME, SIZE, TV, PROJECTOR, SPEAKER) VALUES (992, 2, 2, 'Naranja', 6, FALSE, TRUE, TRUE);
INSERT INTO ROOMS (ID, FLOOR, NUMBER, NAME, SIZE, TV, PROJECTOR, SPEAKER) VALUES (991, 2, 3, 'Gris', 4, FALSE, FALSE, FALSE);
INSERT INTO ROOMS (ID, FLOOR, NUMBER, NAME, SIZE, TV, PROJECTOR, SPEAKER) VALUES (990, 3, 1, 'Rosa', 3, FALSE, FALSE, TRUE);